# Generated by Django 5.1.6 on 2025-12-05 09:59

import django.contrib.postgres.fields
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('micros', models.JSONField(blank=True, null=True)),
                ('allergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('A', 'Cereals containing gluten (wheat, rye, barley, oats)'), ('B', 'Crustaceans (crabs, prawns, lobsters)'), ('C', 'Eggs'), ('D', 'Fish'), ('E', 'Peanuts'), ('F', 'Soybeans'), ('G', 'Milk'), ('H', 'Nuts (almonds, hazelnuts, walnuts, cashews, pecan, brazil, pistachio, macadamia)'), ('L', 'Celery'), ('M', 'Mustard'), ('N', 'Sesame seeds'), ('O', 'Sulphur dioxide / sulphites >10 mg/kg or >10 mg/L'), ('P', 'Lupin'), ('R', 'Molluscs (mussels, oysters, squid, snails)')], max_length=1), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('text', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe_type', models.CharField(blank=True, choices=[('meat', 'Meat'), ('fish', 'Fish'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], max_length=10, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='food.RecipeIngredient', to='food.ingredient'),
        ),
    ]
