# Generated by Django 5.1.6 on 2026-04-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
