# Generated by Django 5.1.6 on 2026-04-10 19:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_ingredient_carbs_alter_ingredient_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetranslation',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
