# Generated by Django 5.1.6 on 2026-04-18 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_recipe_servings'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='food.ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'language_code')},
            },
        ),
    ]
