# Generated by Django 5.1.6 on 2026-04-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_ingredienttranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('bg', 'Български'), ('de', 'Deutsch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (l)'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('pc', 'Piece'), ('pinch', 'Pinch'), ('dash', 'Dash'), ('clove', 'Clove'), ('slice', 'Slice')], max_length=20, null=True),
        ),
    ]
