# Generated by Django 5.1.6 on 2026-05-27 14:46

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_ingredienttranslation_language_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
