# Generated by Django 5.1.6 on 2026-05-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_recipe_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('cup', 'cup'), ('tbsp', 'tbsp'), ('tsp', 'tsp'), ('pc', 'piece'), ('pinch', 'pinch'), ('dash', 'dash'), ('clove', 'clove'), ('slice', 'slice')], max_length=20, null=True),
        ),
    ]
