# Generated by Django 5.1.6 on 2026-09-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['-week_start']},
        ),
        migrations.AlterModelOptions(
            name='mealplanitem',
            options={'ordering': ['day']},
        ),
        migrations.AlterUniqueTogether(
            name='mealplanitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='user',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mealplanitem',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AddConstraint(
            model_name='mealplanitem',
            constraint=models.UniqueConstraint(fields=('meal_plan', 'day'), name='unique_recipe_per_plan_day'),
        ),
        migrations.RemoveField(
            model_name='mealplanitem',
            name='meal_type',
        ),
    ]
