# Generated by Django 5.1.6 on 2025-12-05 13:20

import django.contrib.postgres.search
import django.db.models.deletion
import parler.fields
import parler.models
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_urls', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Pregnancy', 'Pregnancy'), ('Sleep', 'Sleep'), ('Behaviour', 'Behaviour'), ('None', 'None'), ('Health', 'Health'), ('Diet & Nutrition', 'Diet & Nutrition'), ('Fitness', 'Fitness'), ('Toys & Play', 'Toys & Play'), ('Safety', 'Safety'), ('Family Travel', 'Family Travel'), ('Clothing', 'Clothing'), ('Mental Health', 'Mental Health'), ('Baby Gear', 'Baby Gear'), ('Education', 'Education'), ('Relationship', 'Relationship')], default='None', max_length=25)),
                ('is_published', models.BooleanField(default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='articles.article')),
            ],
            options={
                'verbose_name': 'article Translation',
                'db_table': 'articles_article_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['search_vector'], name='articles_ar_search__6714f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articletranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
