# Generated by Django 5.1.5 on 2025-02-05 13:02

import django.contrib.postgres.search
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('media_urls', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Pregnancy', 'Pregnancy'), ('Sleep', 'Sleep'), ('Behaviour', 'Behaviour'), ('None', 'None'), ('Health', 'Health'), ('Diet & Nutrition', 'Diet & Nutrition'), ('Fitness', 'Fitness'), ('Toys & Play', 'Toys & Play'), ('Safety', 'Safety'), ('Family Travel', 'Family Travel'), ('Clothing', 'Clothing'), ('Mental Health', 'Mental Health'), ('Baby Gear', 'Baby Gear'), ('Education', 'Education'), ('Relationship', 'Relationship'), ('Helpful', 'Helpful')], default='None', max_length=25)),
                ('is_published', models.BooleanField(default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
