# Generated by Django 5.1.6 on 2026-02-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='media_urls',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail image for the article', null=True, upload_to='articles/thumbnails/'),
        ),
    ]
