# Generated by Django 5.1.6 on 2026-02-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_media_urls_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail image for the article', null=True, upload_to='thumbnails/'),
        ),
    ]
