# Generated by Django 5.1.6 on 2025-12-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_content_bg_article_content_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Pregnancy', 'Pregnancy'), ('Sleep', 'Sleep'), ('Behaviour', 'Behaviour'), ('None', 'None'), ('Health', 'Health'), ('Diet & Nutrition', 'Diet & Nutrition'), ('Fitness', 'Fitness'), ('Toys & Play', 'Toys & Play'), ('Safety', 'Safety'), ('Family Travel', 'Family Travel'), ('Clothing', 'Clothing'), ('Mental Health', 'Mental Health'), ('Baby Gear', 'Baby Gear'), ('Education', 'Education'), ('Relationship', 'Relationship')], default='None', max_length=25),
        ),
    ]
