# Generated by Django 5.1.6 on 2026-05-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='shared_with',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
